# Generated by Django 2.2.11 on 2020-03-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='happiness',
            field=models.DecimalField(decimal_places=0, default=6, max_digits=2),
        ),
        migrations.AddField(
            model_name='cats',
            name='hunger',
            field=models.DecimalField(decimal_places=0, default=3, max_digits=2),
        ),
    ]
