# Generated by Django 2.2.11 on 2020-03-10 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_auto_20200310_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='cats',
            name='count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2),
        ),
    ]
